[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet OhbPortal.Web.dll"
healthcheckPath = "/Account/Login"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
